name: build check

on:
  push:
    branches: [ "main", "develop" ]
    paths-ignore: [".github/**"]

  pull_request:
    branches: [ "main", "develop" ]
    paths-ignore: [".github/**"]

  workflow_dispatch:

jobs:
  build_project:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.0
        with:
            node-version: 14.20.1

      - uses: actions/checkout@v3

      - name: Install latest npm version
        run: npm install -g npm

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build
